"""add payment methods

Revision ID: 3ab277fa220b
Revises: e8d78c29ef85
Create Date: 2026-02-26 02:17:43.489409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab277fa220b'
down_revision = 'e8d78c29ef85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=30), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exp_month >= 1 AND exp_month <= 12', name='ck_pm_exp_month_range'),
    sa.CheckConstraint('exp_year >= 2020', name='ck_pm_exp_year_min'),
    sa.CheckConstraint('length(last4) = 4', name='ck_pm_last4_len4'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_method_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_method_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_method_is_default'))

    op.drop_table('payment_method')
    # ### end Alembic commands ###
