"""add updated_at to booking

Revision ID: 6ecf630155b7
Revises: a44ff0ee29d7
Create Date: 2026-02-24 02:07:52.650328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6ecf630155b7"
down_revision = "a44ff0ee29d7"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    # ✅ 1) Create ENUM type first (Postgres requirement)
    bookingstatus_enum = postgresql.ENUM(
        "pending", "accepted", "completed", "canceled",
        name="bookingstatus"
    )
    bookingstatus_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table("barber_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("base_price_cents", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.drop_constraint(batch_op.f("barber_profile_user_id_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_barber_profile_user_id"), ["user_id"], unique=True)
        batch_op.drop_column("base_price")

    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False)
        )

        # ✅ 2) VARCHAR -> TIMESTAMP needs USING
        batch_op.alter_column(
            "scheduled_at",
            existing_type=sa.VARCHAR(length=40),
            type_=sa.DateTime(),
            existing_nullable=False,
            postgresql_using="scheduled_at::timestamp without time zone",
        )

        # ✅ 3) Convert status column to ENUM type (now exists)
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            type_=bookingstatus_enum,
            existing_nullable=False,
            postgresql_using="status::bookingstatus",
        )

        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

        batch_op.create_index(batch_op.f("ix_booking_barber_id"), ["barber_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_scheduled_at"), ["scheduled_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_status"), ["status"], unique=False)
        batch_op.create_unique_constraint("uq_booking_barber_time", ["barber_id", "scheduled_at"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_constraint(batch_op.f("user_email_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_role"), ["role"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_role"))
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.create_unique_constraint(
            batch_op.f("user_email_key"),
            ["email"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_constraint("uq_booking_barber_time", type_="unique")
        batch_op.drop_index(batch_op.f("ix_booking_status"))
        batch_op.drop_index(batch_op.f("ix_booking_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_booking_client_id"))
        batch_op.drop_index(batch_op.f("ix_booking_barber_id"))

        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

        # ENUM -> VARCHAR
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "pending", "accepted", "completed", "canceled",
                name="bookingstatus"
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
            postgresql_using="status::text",
        )

        # TIMESTAMP -> VARCHAR
        batch_op.alter_column(
            "scheduled_at",
            existing_type=sa.DateTime(),
            type_=sa.VARCHAR(length=40),
            existing_nullable=False,
            postgresql_using="scheduled_at::text",
        )

        batch_op.drop_column("updated_at")

    with op.batch_alter_table("barber_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("base_price", sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f("ix_barber_profile_user_id"))
        batch_op.create_unique_constraint(
            batch_op.f("barber_profile_user_id_key"),
            ["user_id"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("base_price_cents")

    # ✅ Drop enum type if exists (after column no longer uses it)
    bookingstatus_enum = postgresql.ENUM(
        "pending", "accepted", "completed", "canceled",
        name="bookingstatus"
    )
    bookingstatus_enum.drop(bind, checkfirst=True)