"""booking partial unique index active slots

Revision ID: b6e3ce5f9929
Revises: 6ecf630155b7
Create Date: 2026-02-25 02:08:57.831596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e3ce5f9929'
down_revision = '6ecf630155b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_booking_barber_time'), type_='unique')
        batch_op.create_index('uq_booking_barber_time_active', ['barber_id', 'scheduled_at'], unique=True, postgresql_where=sa.text("status IN ('pending','accepted')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index('uq_booking_barber_time_active', postgresql_where=sa.text("status IN ('pending','accepted')"))
        batch_op.create_unique_constraint(batch_op.f('uq_booking_barber_time'), ['barber_id', 'scheduled_at'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
