"""add reset password fields

Revision ID: e8d78c29ef85
Revises: b6e3ce5f9929
Create Date: 2026-02-26 01:57:09.196440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d78c29ef85'
down_revision = 'b6e3ce5f9929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_booking_barber_time_active'), postgresql_where="(status = ANY (ARRAY['pending'::bookingstatus, 'accepted'::bookingstatus]))")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_booking_barber_time_active'), ['barber_id', 'scheduled_at'], unique=True, postgresql_where="(status = ANY (ARRAY['pending'::bookingstatus, 'accepted'::bookingstatus]))")

    # ### end Alembic commands ###
